### ISSUE TITLE
Unable to install in FreeBSD14.1

### ISSUE THREAD

**Issue by souradeep100** [shell-pool/shpool#143]
**What happened**
cargo install is failing with libproc build

**What I expected to happen**
cargo install of other crates are successful.

**To Reproduce**
cargo install shpool

error: failed to compile `shpool v0.7.0`,

   Compiling shpool-protocol v0.2.0
   Compiling libproc v0.14.8
error[E0601]: `main` function not found in crate `build_script_build`
  --> /home/schakrabarti/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libproc-0.14.8/build.rs:23:13
   |
23 | fn main() {}
   |             ^ consider adding a `main` function to `/home/schakrabarti/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libproc-0.14.8/build.rs`

**Comment by ethanpailes** [comment]
I don't think we use libproc for too much, so we can probably condition this out for freebsd. For now, you can try seeing if 0.6.3 or 0.6.2 will build for you since I think we added libproc somewhat recently. You could also try reporting the issue upstream since libproc is supposed to be a cross platform crate.

**Comment by souradeep100** [comment]
Hi tried version 0.6.0 and following error during install was coming

Compiling termini v1.0.0
   Compiling tempfile v3.12.0
   Compiling shpool_vt100 v0.1.2
error: failed to run custom build command for `motd v0.2.2`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installZ58FUj/release/build/motd-61bbca1f94cea17d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/pam_motd_overlay.c
  cargo:rerun-if-changed=src/pam_motd_overlay_versions.ldscript

  --- stderr
  thread 'main' panicked at /home/schakrabarti/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motd-0.2.2/build.rs:23:13:
  build failed: error building overlay, code = exit status: 1
  STDOUT:
  STDERR: ./src/pam_motd_overlay.c:11:10: fatal error: 'security/_pam_types.h' file not found
  #include <security/_pam_types.h>
           ^~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `shpool v0.6.0`, intermediate artifacts can be found at `/tmp/cargo-installZ58FUj`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
[schakrabarti@schakrabarti-freebsd4 ~]$

**Comment by ethanpailes** [comment]
That build issue should be fixed in later version. Does a version between 0.6.0 and 0.7.0 work for you?

**Comment by souradeep100** [comment]
No, none of them are getting installed. I guess there is some tight dependency for Linux here.

**Comment by ethanpailes** [comment]
@souradeep100 are you able to have any better luck with the latest version of shpool? The motd crate should no longer be compiling c code and we've been avoiding bumping our MSRV for a while now in the hopes of improving portability.

**Comment by souradeep100** [comment]
I have tried with 0.8 and still no luck. I am not getting enough time from my current projects to work on it.  ☹️

**Comment by souradeep100** [comment]
error[E0601]: `main` function not found in crate `build_script_build`
  --> /home/schakrabarti/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libproc-0.14.10/build.rs:23:13
   |
23 | fn main() {}
   |             ^ consider adding a `main` function to `/home/schakrabarti/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libproc-0.14.10/build.rs`

For more information about this error, try `rustc --explain E0601`.
error: could not compile `libproc` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `shpool v0.8.0`, intermediate artifacts can be found at `/tmp/cargo-installXzERbX`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
schakrabarti ~
>

**Comment by ethanpailes** [comment]
We might want to just remove the libproc dependency. I'm not sure it is worth the portability issues.

**Comment by ethanpailes** [comment]
It seems like freebsd doesn't support `/proc/<pid>/exe` so there isn't much point in rolling back libproc as a dep since it won't really help. We would need to implement our own cross platform wrapper layer that uses libproc on mac and linux and something special to map pid to binary name on freebsd.

If someone wants to take on a freebsd port, I'll be happy to take patches, but I'm probably not going to drive it forward myself.
